// <auto-generated />
namespace Gas_Go_v1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class role : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(role));
        
        string IMigrationMetadata.Id
        {
            get { return "201909151653151_role"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
