//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gas_Go_v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GasStations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GasStations()
        {
            this.RequestResult = new HashSet<RequestResult>();
        }
    
        public int GasStationId { get; set; }
        public string GasStationName { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Street { get; set; }
        public string Suburb { get; set; }
        public decimal Longitude { get; set; }
        public decimal Latitude { get; set; }
        public Nullable<decimal> UnleadedPrice { get; set; }
        public Nullable<System.DateTime> UnleadedPriceUpdatedTime { get; set; }
        public Nullable<decimal> Premium95Price { get; set; }
        public Nullable<System.DateTime> Premium95PriceUpdatedTime { get; set; }
        public Nullable<decimal> Premium98Price { get; set; }
        public Nullable<System.DateTime> Premium98PriceUpdatedTime { get; set; }
        public Nullable<decimal> DieselPrice { get; set; }
        public Nullable<System.DateTime> DieselPriceUpdatedTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestResult> RequestResult { get; set; }
    }
}
