//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gas_Go_v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestResult
    {
        public int ResultId { get; set; }
        public System.DateTime ResultDateTime { get; set; }
        public Nullable<int> RequestID { get; set; }
        public string UserID { get; set; }
        public int GasStationID { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual GasStations GasStations { get; set; }
        public virtual UserSearchRequest UserSearchRequest { get; set; }
    }
}
